### ISSUE TITLE
Add a README pls

### ISSUE THREAD

**Issue by utybo** [gastbob40/epimodo_bot#3]
The readme should contain:

* [x] General description
* [x] Basic setup and running instructions
* [x] Basic developer environment setup instructions (how to get started coding on epimodo)
* [ ] Authors
* [ ] Other important details (e.g. security concerns)

**Comment by gastbob40** [comment]
What do you think about the new readme ?

**Comment by utybo** [comment]
Looks pretty good overall. I'll make a small PR because the Windows venv activation instructions are not accurate.

**Comment by gastbob40** [comment]
Merged

**Comment by utybo** [comment]
Thanks! Closing this issue.
